services:
    directus:
        image: directus/directus:latest
        ports:
            - 8055:8055
        volumes:
            - ./database:/directus/database
            - ./uploads:/directus/uploads
            - ./extensions:/directus/extensions
        environment:
            SECRET: "sih-2024"
            ADMIN_EMAIL: "admin@mppolice.gov.in"
            ADMIN_PASSWORD: "1234"
            DB_CLIENT: "sqlite3"
            DB_FILENAME: "/directus/database/data.db"
            WEBSOCKETS_ENABLED: "true"